services:
  literaturaDB:
    image: postgres:15.3
    container_name: my-literaturaDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=172922
      - POSTGRES_DB=literatura-db
    volumes:
      - ./postgres:/var/lib/postgresql/data